---
- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
